// Generated by CoffeeScript 1.7.1
(function() {
  var KnowledgeNet;

  KnowledgeNet = (function() {
    function KnowledgeNet(json_obj) {
      this._raw_points = json_obj['knowledge_points'];
      this._raw_edges = json_obj['links'];
      this._build();
    }

    KnowledgeNet.prototype._build = function() {
      var child_id, e, p, parent_id, _i, _j, _len, _len1, _ref, _ref1, _results;
      this._points_map = {};
      _ref = this._raw_points;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        this._points_map[p.id] = p;
        this._points_map[p.id]['edges'] = [];
        this._points_map[p.id]['parents'] = [];
        this._points_map[p.id]['children'] = [];
      }
      _ref1 = this._raw_edges;
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        e = _ref1[_j];
        parent_id = e['parent_id'];
        child_id = e['child_id'];
        this._points_map[parent_id]['edges'].push([parent_id, child_id]);
        this._points_map[parent_id]['children'].push(child_id);
        this._points_map[child_id]['edges'].push([parent_id, child_id]);
        _results.push(this._points_map[child_id]['parents'].push([parent_id]));
      }
      return _results;
    };

    KnowledgeNet.prototype.points = function() {
      var key;
      if (!this._points) {
        this._points = [];
        for (key in this._points_map) {
          this._points.push(this._points_map[key]);
        }
      }
      return this._points;
    };

    KnowledgeNet.prototype.edges = function() {
      return this._raw_edges;
    };

    KnowledgeNet.prototype.find_by = function(id) {
      return this._points_map[id];
    };

    KnowledgeNet.prototype.roots = function() {
      var key, p;
      if (!this._roots) {
        this._roots = [];
        for (key in this._points_map) {
          p = this._points_map[key];
          if (p.parents.length === 0) {
            this._roots.push(p);
          }
        }
      }
      return this._roots;
    };

    return KnowledgeNet;

  })();

  window.KnowledgeNet = KnowledgeNet;

}).call(this);
