// Generated by CoffeeScript 1.7.1
(function() {
  var KnowledgeNetGraph,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    if (jQuery('body.sample').length) {
      return jQuery.getJSON('data/js/js.json', function(data) {
        return new KnowledgeNetGraph(jQuery('.graph-paper'), data);
      });
    }
  });

  KnowledgeNetGraph = (function() {
    function KnowledgeNetGraph($elm, data) {
      this.$elm = $elm;
      this.data = data;
      this.__zoom = __bind(this.__zoom, this);
      this.SCALE = [0.25, 2];
      this.offset_x = 0;
      this.offset_y = 0;
      this.knet = new KnowledgeNet(this.data);
      this.draw();
    }

    KnowledgeNetGraph.prototype.draw = function() {
      this._svg();
      return this._tree();
    };

    KnowledgeNetGraph.prototype._svg = function() {
      var zoom_behavior;
      zoom_behavior = d3.behavior.zoom().scaleExtent(this.SCALE).on('zoom', this.__zoom);
      this.svg = d3.select(this.$elm[0]).append('svg').attr('class', 'knsvg').call(zoom_behavior);
      return this.graph = this.svg.append('g');
    };

    KnowledgeNetGraph.prototype.__zoom = function() {
      var scale, translate;
      scale = d3.event.scale;
      this.__toggle_text_by_scale(scale);
      translate = d3.event.translate;
      return this.graph.attr('transform', "translate(" + (translate[0] + this.offset_x * scale) + ", " + translate[1] + ") scale(" + scale + ")");
    };

    KnowledgeNetGraph.prototype.__toggle_text_by_scale = function(scale) {
      if (scale < 0.8) {
        return this.text.attr('class', 'hide');
      } else {
        return this.text.attr('class', null);
      }
    };

    KnowledgeNetGraph.prototype._tree = function() {
      var diagonal, first_node, links, node_enter, nodes, obj, tree, tree_data;
      tree_data = this.knet.get_tree_nesting_data();
      obj = {
        name: 'ROOT',
        children: tree_data
      };
      tree = d3.layout.tree().nodeSize([80, 100]).separation(function(a, b) {
        if (a.parent === b.parent) {
          return 1;
        } else {
          return 2;
        }
      });
      diagonal = d3.svg.diagonal().projection(function(d) {
        return [d.x, d.y];
      });
      nodes = tree.nodes(obj);
      links = tree.links(nodes);
      first_node = tree_data[0];
      this.offset_x = -first_node.x + 300;
      this.graph.attr('transform', "translate(" + this.offset_x + ", 0)");
      node_enter = this.graph.selectAll('.node').data(nodes).enter().append('g').attr('class', 'node').attr('transform', function(d) {
        return "translate(" + d.x + ", " + d.y + ")";
      });
      node_enter.append('circle').attr('r', 15).style('fill', '#232B2D').style('stroke', '#65B2EF').style('stroke-width', 5).style('display', function(d) {
        if (d.name === 'ROOT') {
          return 'none';
        }
      });
      this.text = node_enter.append('text').attr('dy', 45).attr('text-anchor', 'middle').text(function(d) {
        return d.name;
      }).style('font-family', 'arial, 微软雅黑').style('font-size', '14px').style('fill', '#fff').style('display', function(d) {
        if (d.name === 'ROOT') {
          return 'none';
        }
      });
      return this.graph.selectAll('.link').data(links).enter().insert('path', 'g').attr('class', 'link').attr('d', diagonal).style('fill', 'none').style('stroke', '#6F7B7E').style('stroke-width', '3px').style('display', function(d) {
        if (d.source.name === 'ROOT') {
          return 'none';
        }
      });
    };

    return KnowledgeNetGraph;

  })();

}).call(this);

//# sourceMappingURL=ui.map
