// Generated by CoffeeScript 1.7.1
(function() {
  var KnowledgeNetGraph,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  jQuery(function() {
    if (jQuery('body.sample').length) {
      return jQuery.getJSON('data/js/js.json', function(data) {
        return new KnowledgeNetGraph(jQuery('.graph-paper'), data);
      });
    }
  });

  KnowledgeNetGraph = (function() {
    function KnowledgeNetGraph($elm, data) {
      this.$elm = $elm;
      this.data = data;
      this.__zoom = __bind(this.__zoom, this);
      this.SCALE = [0.25, 2];
      this.IMAGINARY_ROOT_NAME = 'IROOT';
      this.BASE_OFFSET_X = 300;
      this.offset_x = 0;
      this.offset_y = 0;
      this.knet = new KnowledgeNet(this.data);
      this.draw();
    }

    KnowledgeNetGraph.prototype.draw = function() {
      this._svg();
      this._tree();
      this._links();
      return this._nodes();
    };

    KnowledgeNetGraph.prototype._svg = function() {
      var zoom_behavior;
      zoom_behavior = d3.behavior.zoom().scaleExtent(this.SCALE).on('zoom', this.__zoom);
      this.svg = d3.select(this.$elm[0]).append('svg').attr('class', 'knsvg').call(zoom_behavior);
      return this.graph = this.svg.append('g');
    };

    KnowledgeNetGraph.prototype.__zoom = function() {
      var scale, translate;
      scale = d3.event.scale;
      translate = d3.event.translate;
      this.__set_text_class(scale);
      return this.graph.attr('transform', "translate(" + (translate[0] + this.offset_x * scale) + ", " + translate[1] + ") scale(" + scale + ")");
    };

    KnowledgeNetGraph.prototype.__set_text_class = function(scale) {
      var klass;
      klass = ['name'];
      if (scale < 0.7) {
        klass.push('hide');
      }
      return this.name_texts.attr('class', (function(_this) {
        return function(d) {
          if (d.name === _this.IMAGINARY_ROOT_NAME) {
            return "iroot " + klass.join(' ');
          } else {
            return klass.join(' ');
          }
        };
      })(this));
    };

    KnowledgeNetGraph.prototype._tree = function() {
      var first_node, imarginay_root;
      this.tree_data = this.knet.get_tree_nesting_data();
      imarginay_root = {
        name: this.IMAGINARY_ROOT_NAME,
        children: this.tree_data.roots
      };
      this.tree = d3.layout.tree().nodeSize([80, 160]);
      this.nodes = this.tree.nodes(imarginay_root);
      first_node = this.tree_data.roots[0];
      this.offset_x = -first_node.x + this.BASE_OFFSET_X;
      return this.graph.attr('transform', "translate(" + this.offset_x + ", 0)");
    };

    KnowledgeNetGraph.prototype._nodes = function() {
      var enter;
      enter = this.graph.selectAll('.node').data(this.nodes).enter().append('g').attr('class', 'node').attr('transform', function(d) {
        return "translate(" + d.x + ", " + d.y + ")";
      });
      this.circles = enter.append('circle').attr('r', 15).attr('class', (function(_this) {
        return function(d) {
          var klass;
          klass = [];
          if (d.name === _this.IMAGINARY_ROOT_NAME) {
            klass.push('iroot');
          }
          if (d.depth === 1) {
            klass.push('start-point');
          }
          return klass.join(' ');
        };
      })(this));
      this.name_texts = enter.append('text').attr('dy', 45).attr('text-anchor', 'middle').text(function(d) {
        return d.name;
      });
      return this.__set_text_class(1);
    };

    KnowledgeNetGraph.prototype._links = function() {
      var links;
      links = this.tree_data.edges;
      return this.graph.selectAll('.link').data(links).enter().append('path').attr('d', d3.svg.diagonal()).attr('class', (function(_this) {
        return function(d) {
          if (d.source.name === _this.IMAGINARY_ROOT_NAME) {
            return 'iroot link';
          } else {
            return 'link';
          }
        };
      })(this));
    };

    return KnowledgeNetGraph;

  })();

}).call(this);

//# sourceMappingURL=ui.map
